dashboard/urls.py
from django.conf.urls import url

from . import views

app_name = 'dashboard'

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

hospital/urls.py
from django.conf.urls import include , url
#from django.contrib import admin

from . import views

urlpatterns = [
#    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^logout/',  views.logoutapp, name='logoutapp'),
    url(r'^patients/', include('patients.urls')),
    url(r'^dashboard/', include('dashboard.urls')),
]

patients/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

dashboard/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

patients/models.py
from __future__ import unicode_literals
from django.core.validators import RegexValidator

from django.db import models

# Create your models here.

class Patient(models.Model):
	#id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    dob = models.DateTimeField('Patient Age Date of Birth')
    dod = models.DateTimeField('Patient Date of Death',null=True, blank=True)
    height = models.IntegerField(default=0)
    weight = models.IntegerField(default=0)
    gender = models.CharField(max_length=200)
    nationality = models.CharField(max_length=200)
    colour = models.CharField(max_length=200)
    email = models.EmailField(blank=True)
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
    phone_number = models.CharField(validators=[phone_regex], blank=True ,max_length=15) # validators should be a list

dashboard/views.py
from django.http import HttpResponse
from django.shortcuts import render , redirect



# Create your views here.

def index(request):
    return render(request,'dashboard/index.html')

hospital/views.py
from django.http import HttpResponse , JsonResponse 
from django.shortcuts import render , redirect
from django.template import RequestContext
from django.contrib.auth import authenticate, login, logout
from django.views.decorators.http import require_http_methods
from django.core import serializers
import json


# Create your views here.
@require_http_methods(["GET", "POST"])
def index(request):
  if request.user.is_authenticated():
     #return redirect('/dashboard/')
     return render(request,'dashboard/index.html',context_instance=RequestContext(request))
  else:
    if request.method == 'GET':
       return render(request,'hospital/login.html',context_instance=RequestContext(request))
    elif  request.is_ajax() or request.method == 'POST':
        #errors = []
        ret = {}
        #data = serializers.serialize("json",errors)
        body_unicode = request.body.decode('utf-8')
        body = json.loads(body_unicode)
        username = body['username']
        password = body['password']
        user = authenticate(username=username, password=password)
        
        if user is not None:
			if user.is_active:
				login(request , user)
				ret['status']= ['ok']
				return JsonResponse(json.dumps(ret),safe=False)
				#return redirect('/dashboard/')
			else :
				#errors.append('account is disabled')
				ret['errors']= ['account is disabled']
				return JsonResponse(json.dumps(ret),safe=False)
        else:
			#errors.append(['login error'])
			ret['errors']= ['login error']
			ret['username']= username
			
			return JsonResponse(json.dumps(ret),safe=False)

def logoutapp(request):
    logout(request)
    return redirect('/')

patients/views.py
from django.http import HttpResponse
from django.shortcuts import render , redirect



# Create your views here.

def index(request):
    return HttpResponse("Hello, world. You're at the Patient index.")

templates/dashboard/index.html
{% extends 'hospital/base.html' %}

{% block content %}
{% if user.is_authenticated %}

  <div class="medium-12 columns ">
    <router-view></router-view>

  </div>

{% endif %}
{% endblock  %}

templates/hospital/base.html
{% load i18n staticfiles %}
<!doctype html>
{% get_current_language as LANGUAGE_CODE %}{% get_current_language_bidi as LANGUAGE_BIDI %}
<html class="no-js" lang="{{ LANGUAGE_CODE|default:"en-us" }}" {% if LANGUAGE_BIDI %}dir="rtl"{% endif %}>

<head>
<meta http-equiv="x-ua-compatible" content="ie=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>{% block title %}{% endblock %}</title>

<!-- Main Framework foundation css-->
<link rel="stylesheet" href="{% static "hospital/css/framework.css" %}" />

<!-- Vendor styles  -->
<link rel="stylesheet" type="text/css" href="{% static "hospital/fonts/foundation-icon-fonts/foundation-icons.css" %}" />
<link rel="stylesheet" type="text/css" href="{% static "hospital/fonts/font-awesome/css/font-awesome.min.css" %}" />
<link rel="stylesheet" type="text/css" href="{% static "hospital/fonts/Dripicons/css/dripicons.css" %}" />
<link rel="stylesheet" type="text/css" href="{% static "hospital/fonts/typicons.font/src/font/typicons.css" %}" />


<!-- lib css  -->
<link rel="stylesheet" type="text/css" href="{% static "hospital/css/lib.min.css" %}" />

<!-- main css  -->
<link rel="stylesheet" type="text/css" href="{% static "hospital/css/app.css" %}" />



<!-- pace loader -->
<!-- <script  src="{% static "hospital/vendors/PACE/pace.js" %}" ></script>   -->
<link rel="stylesheet" type="text/css" href="{% static "hospital/vendors/PACE/themes/orange/pace-theme-flash.css" %}" />

</head>

<body>


<!-- Start off-canvas-wrapper -->
<div class="off-canvas-wrapper">

<!-- Start off-canvas-wrapper-inner -->
<div class="off-canvas-wrapper-inner"  data-off-canvas-wrapper>

<!-- Start off-canvas right menu  -->
 <div class="off-canvas position-right" id="offCanvasRight" data-off-canvas data-position="right"></div>
<!-- End of off-canvas right menu  -->

<!-- Start off-canvas content -->
<div class="off-canvas-content" id="" data-off-canvas-content>
	
<!-- preloader -->
<div id="preloader">
<div id="status">&nbsp;</div>
</div>

<div class="grid">
	{% if user.is_authenticated %}
      <sidebarmenu v-ref:leftmenu  logo="{% static "hospital/img/logo.png" %}" :allroutes="routes" ></sidebarmenu>
    <!-- sidebar -->
    {% endif %}
  <!-- main content container -->
  <div class="grid__col-sm-auto grid__col--bleed" id="Hp-maincontent">
	  
	  {% if user.is_authenticated %}
	  <topbar logout="{% url 'logoutapp' %}"></topbar>
      <!-- Topbar -->
      {% endif %}
     
      <div class="row">
      {% block content %}
	    
		
	  {% endblock %}  
      </div>
  
  
  </div>
 <!-- End main content container -->
 
</div>

</div>
<!-- End off-canvas content  -->



</div>
<!-- end of off-canvas-wrapper-inner -->

</div>
<!-- end of off-canvas-wrapper -->



<!-- main javascript library -->
<!-- <script  src="{% static "hospital/js/jquery.js" %}" ></script> -->
<!--<script  src="{% static "hospital/js/jquery.waypoints.min.js" %}" ></script> -->


<!-- foundation javascript -->
<!-- <script  src="{% static "hospital/js/what-input.min.js" %}" ></script>  -->
<!--<script  src="{% static "hospital/js/foundation.min.js" %}" ></script> -->

<!-- lib javascript -->
<!--<script  src="{% static "hospital/js/lib.js" %}" ></script> -->

<!-- main theme javascript -->

<!-- <script  src="{% static "hospital/js/app.js" %}" ></script>  -->
<script  src="{% static "hospital/js/build.js" %}" ></script>



</body>

</html>

templates/hospital/login.html
{% extends 'hospital/base.html' %}

{% block content %}
{% if user.is_anonymous %}

  <div class="medium-6 medium-centered large-6 large-centered column ">

    
      <div class="row column log-in-form">
		  <login dashurl="{% url 'dashboard:index' %}"></login>
      </div>
    

  </div>

{% endif %}
{% endblock  %}